language: minimal

services:
  - docker

before_script:
  - docker pull 1tgr/websocket-lite:${TRAVIS_BRANCH} || docker pull 1tgr/websocket-lite:master || true
  - docker build --target deps -t 1tgr/websocket-lite-deps .

script:
  - docker build --target app -t 1tgr/websocket-lite:latest . && docker-compose up --exit-code-from test

after_script:
  - docker tag 1tgr/websocket-lite:latest 1tgr/websocket-lite:${TRAVIS_BRANCH}
  - docker push 1tgr/websocket-lite:${TRAVIS_BRANCH}
