version: '3.2'

services:
  fuzzingserver:
    image: 1tgr/websocket-lite
    command: wstest -m fuzzingserver --spec config/fuzzingserver.json
    volumes:
      - ./config:/app/config
      - ./reports:/app/reports

  python-hello-world-server:
    image: 1tgr/websocket-lite
    command: python3 /app/hello_world_server.py
    volumes:
      - ./hello_world_server.py:/app/hello_world_server.py

  hyper-autobahn-server:
    image: 1tgr/websocket-lite
    command: ./autobahn-server

  hyper-hello-world-server:
    image: 1tgr/websocket-lite
    command: ./hello-world-server 9001

  test:
    image: 1tgr/websocket-lite
    command: ./test.sh
    depends_on:
      - fuzzingserver
      - python-hello-world-server
      - hyper-hello-world-server
    volumes:
      - ./config:/app/config
      - ./reports:/app/reports
      - ./test.sh:/app/test.sh
