version: '3.2'

services:
  fuzzingserver:
    image: crossbario/autobahn-testsuite:0.8.0
    volumes:
      - ./config:/config:ro
      - ./reports:/reports

  hello-world-server:
    image: python:3.8
    command: bash -c "pip install -r /app/requirements.txt && python /app/hello_world_server.py"
    volumes:
      - .:/app

  test:
    image: 1tgr/websocket-lite
    command: ./test.sh
    depends_on:
      - fuzzingserver
      - hello-world-server
    volumes:
      - ./reports:/reports:ro
      - ./test.sh:/app/test.sh
