name: CI

on: [push, pull_request]

jobs:
  cargo-build:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub login
      run: docker login --username 1tgr --password ${DOCKER_HUB_TOKEN}
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Pull previous deps
      run: docker pull 1tgr/websocket-lite-deps
    - name: Pull master build
      run: docker pull 1tgr/websocket-lite-build:master
    - name: Pull previous build
      continue-on-error: true
      run: docker pull 1tgr/websocket-lite-build:${GITHUB_REF##*/}
    - name: Build deps
      run: >-
        docker build
        --cache-from 1tgr/websocket-lite-deps
        --target deps -t 1tgr/websocket-lite-deps:latest
        .
    - name: cargo build
      run: >-
        docker build
        --cache-from 1tgr/websocket-lite-deps
        --cache-from 1tgr/websocket-lite-build:master
        --cache-from 1tgr/websocket-lite-build:${GITHUB_REF##*/}
        --target build
        -t 1tgr/websocket-lite-build:${GITHUB_REF##*/}
        .
    - name: Push current deps
      if: github.ref == 'refs/heads/master'
      run: docker push 1tgr/websocket-lite-deps:latest
    - name: Push current build
      run: docker push 1tgr/websocket-lite-build:${GITHUB_REF##*/}

  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    needs: cargo-build
    steps:
    - uses: actions/checkout@v2
    - name: Pull current build
      run: docker pull 1tgr/websocket-lite-build:${GITHUB_REF##*/}
    - name: cargo test
      run: >-
        docker run
        1tgr/websocket-lite-build:${GITHUB_REF##*/}
        cargo test --release

  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    needs: cargo-build
    steps:
    - uses: actions/checkout@v2
    - name: Pull current build
      run: docker pull 1tgr/websocket-lite-build:${GITHUB_REF##*/}
    - name: cargo clippy
      run: >-
        docker run
        1tgr/websocket-lite-build:${GITHUB_REF##*/}
        cargo clippy --release

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: cargo-build
    steps:
    - uses: actions/checkout@v2
    - name: Pull current build
      run: docker pull 1tgr/websocket-lite-build:${GITHUB_REF##*/}
    - name: Build integration test
      run: >-
        docker build
        --cache-from 1tgr/websocket-lite-build:${GITHUB_REF##*/}
        --target app
        -t 1tgr/websocket-lite:latest
        .
    - name: Integration test
      run: docker-compose up --exit-code-from test

  fuzz-test:
    name: Fuzz test
    runs-on: ubuntu-latest
    needs: cargo-build
    steps:
    - uses: actions/checkout@v2
    - name: Pull current build
      run: docker pull 1tgr/websocket-lite-build:${GITHUB_REF##*/}
    - name: Build fuzz test
      run: >-
        docker build
        --cache-from 1tgr/websocket-lite-build:${GITHUB_REF##*/}
        --target fuzz
        -t 1tgr/websocket-lite-fuzz:latest
        .
    - name: Fuzz test
      run: >-
        docker run
        --cap-add SYS_PTRACE
        1tgr/websocket-lite-fuzz:latest
        cargo fuzz run fuzz_codec fuzz/corpus/custom -- -dict=fuzz/dict.txt -max_total_time=60
